version: "2"

plugins:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      # trailing spaces
      MD009:
        enabled: false
      # multiple blank lines
      MD012:
        enabled: false
      # line length
      MD013:
        enabled: false
      # raw html
      MD033:
        enabled: false


exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"